name = "AI Chat Widget"
type = "theme"

[[extensions]]
type = "app_embed"
name = "AI Chat Widget"

  [[extensions.settings]]
  type = "paragraph"
  content = "Display an AI-powered chat widget on your storefront to help customers with product questions, orders, and support."

  [[extensions.settings]]
  type = "text"
  id = "api_url"
  label = "API URL"
  default = "https://shopchatai.indigenservices.com"
  info = "The URL of your chat API server. Do not change unless instructed."

  [[extensions.settings]]
  type = "select"
  id = "position"
  label = "Widget position"
  default = "bottom-right"
  info = "Where the chat button appears on your store"
  options = [
    { value = "bottom-right", label = "Bottom Right" },
    { value = "bottom-left", label = "Bottom Left" },
    { value = "top-right", label = "Top Right" },
    { value = "top-left", label = "Top Left" }
  ]

  [[extensions.settings]]
  type = "color"
  id = "primary_color"
  label = "Primary color"
  default = "#5C6AC4"
  info = "Main color for the chat widget"

  [[extensions.settings]]
  type = "color"
  id = "accent_color"
  label = "Accent color"
  default = "#00848E"
  info = "Accent color for buttons and highlights"

  [[extensions.settings]]
  type = "text"
  id = "welcome_message"
  label = "Welcome message"
  default = "Hi! How can I help you today?"
  info = "First message customers see when opening the chat"
